---
- name: install python-pip
  apt: name=python-pip

- name: install docker-py
  pip: name=docker-py

- name: start a nginx container
  docker_container:
    image: kofonfor/nginx-carbonized:0.1.31
    state: started
    read_only: no
    hostname: "{{ ansible_hostname }}-{{ nginx_container_name }}"
    ports:
      - "{{ docker_nginx_port }}:80"
      - "{{ docker_nginx_ssl_port }}:443"
    volumes:
      - "{{ ext_nginx_logs_volume }}:/var/log/nginx"
      - "{{ ext_nginx_conf_volume }}:/etc/nginx"
      - "{{ ext_nginx_le_volume }}:/etc/letsencrypt"
      - "{{ ext_nginx_varwww_volume }}:/var/www"
    name: "{{ nginx_container_name }}"
    restart_policy: always
  tags:
    - docker
